A: ["a1", "a2", "a3", "a4", "a5", "a6"]
D: ["d1", "d2", "d3", "d4", "d5", "d6", "d7"]
T: ["t1", "t2", "t3"]
S_dt:
  - [2, 2, 2]
  - [2, 2, 2]
  - [2, 2, 2]
  - [2, 2, 2]
  - [2, 2, 2]
  - [2, 2, 2]
  - [2, 2, 2]
R_a: [10 ,4, 11, 7, 6, 5]
G_ga:
  - [1, 1, 0, 0, 0, 0]
  - [0, 0, 1, 1, 0, 0]
  - [0, 0, 0, 0, 1, 1]
r_adt:
  - [[1, 1, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  - [[1, 1, 1], [1, 1, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  - [[1, 1, 1], [1, 1, 1], [1, 0, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  - [[1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  - [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 1, 1], [1, 1, 1], [1, 1, 1]]
  - [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [0, 1, 1]]
algorithm: SQA
num_reads: 100
coeff:
  w_desire:
    ratio: 1.5
  w_group:
    ratio: 5.0
  base: 1.4
output:
  coeff_test: "graph/coeff_ratio.png"
  base_test: "graph/coeff_base.png"
  enegry: "graph/enegry.png"
  schedule: "graph/schedule.png"
algorithm: SQA